---
- hosts: webservers
  become: yes

  tasks:
    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    - name: Pull latest code
      git:
        repo: "https://github.com/username/my-public-repo.git"
        dest: /var/www/my-node-app

    - name: Install dependencies
      command: npm ci chdir=/var/www/my-node-app

    - name: Start app with PM2
      command: pm2 start app.js --name my-node-app chdir=/var/www/my-node-app

