---
- name: Deploy Dockerized App
  hosts: webservers
  become: yes
  vars:
    docker_image: "sami95/my-app:latest"
    container_name: "my_node_app"
  tasks:

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Stop existing container
      docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Run new container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
